# Generated by Django 2.1.5 on 2020-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meal',
            field=models.CharField(blank=True, help_text='Enter the meal you want to eat', max_length=20, null=True),
        ),
    ]
